In [1]:
#Question 1. Create a numpy array starting from 2 till 50 with a stepsize of 3.
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [7]:
#Question 2. Accept two lists of 5 elements each from the user.
#Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print them
l1,l2=[],[]
for i in range(5):
    l = input()
    l1.append(int(l))
for i in range(5):
    m=input()
    l2.append(int(m))
a=np.array(l1)
b=np.array(l2)
c=np.concatenate((a,b))
print(c)
a1=np.sort(a,axis=None)
b1=np.sort(b,axis=None)
print(a1)
print(b1)

5
3
4
2
1
10
7
8
6
9
[ 5  3  4  2  1 10  7  8  6  9]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [8]:
#Question 3 Write a code snippet to find the dimensions of a ndarray and its size.
arr = np.array( [[ 1, 2, 3],
                 [ 4, 9, 5]])
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


In [15]:
#Question 4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
A = np.array([1,2,3,7,89,62])
B = np.reshape(A, (3, 2))
print(A)
print(B)

[ 1  2  3  7 89 62]
[[ 1  2]
 [ 3  7]
 [89 62]]


In [16]:
#Question 5. Consider two square numpy arrays. Stack them vertically and horizontally.
a = np.array([[11, 24], 
              [36, 47]]) 
  
b = np.array([[51, 62], 
              [70, 86]]) 
print("Vertical stacking:\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[11 24]
 [36 47]
 [51 62]
 [70 86]]

Horizontal stacking:
 [[11 24 51 62]
 [36 47 70 86]]


In [23]:
#Question 6. How to get unique items and counts of unique items?
items = np.array([1,2,3,4,5,1,2,1,2,4,5,6,2,2,3,1])
(unique, counts) = np.unique(items, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(f'Element : Count')
for i in frequencies:
    print(f'{i[0]} : {i[1]}')


Element : Count
1 : 4
2 : 5
3 : 2
4 : 2
5 : 2
6 : 1
